# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import Window.NGWindow as NGW
from PyQt5 import QtCore, QtGui, QtWidgets

if __name__ == "__main__":
    import sys
    import zmq

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    ui = NGW.Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()

    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    socket.connect("ipc://NG")
    socket.send(b"Hello")
    message = socket.recv()

    sys.exit(app.exec_())
